-- V9: 操作日志表
CREATE TABLE audit_log (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_id        VARCHAR(64)  COMMENT '链路追踪ID',
    user_id         VARCHAR(64)  NOT NULL,
    username        VARCHAR(64)  NOT NULL,
    user_name       VARCHAR(64)  COMMENT '操作人姓名',
    company_id      BIGINT,
    department_id   BIGINT,
    module          VARCHAR(32)  NOT NULL COMMENT '模块标识',
    action          VARCHAR(32)  NOT NULL COMMENT 'CREATE/UPDATE/DELETE/STATUS_CHANGE/LOGIN/LOGOUT/REGISTER/REGISTRATION_APPROVED/REGISTRATION_REJECTED/EXPORT',
    http_method     VARCHAR(8),
    http_url        VARCHAR(256),
    resource_type   VARCHAR(64)  COMMENT '资源类型',
    resource_id     VARCHAR(64),
    resource_code   VARCHAR(64),
    detail          JSON COMMENT '变更详情JSON',
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(512),
    request_id      VARCHAR(64),
    create_time     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_user_time   (user_id, create_time),
    KEY idx_module_time (module, create_time),
    KEY idx_resource    (resource_type, resource_id),
    KEY idx_time        (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
