CREATE TABLE `audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trace_id` varchar(64) DEFAULT NULL COMMENT '链路追踪ID',
  `user_id` varchar(64) NOT NULL,
  `username` varchar(64) NOT NULL,
  `user_name` varchar(64) DEFAULT NULL COMMENT '操作人姓名',
  `company_id` bigint DEFAULT NULL,
  `department_id` bigint DEFAULT NULL,
  `module` varchar(32) NOT NULL COMMENT '模块标识',
  `action` varchar(32) NOT NULL COMMENT 'CREATE/UPDATE/DELETE/STATUS_CHANGE/LOGIN/LOGOUT/REGISTER/REGISTRATION_APPROVED/REGISTRATION_REJECTED/EXPORT',
  `http_method` varchar(8) DEFAULT NULL,
  `http_url` varchar(256) DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL COMMENT '资源类型',
  `resource_id` varchar(64) DEFAULT NULL,
  `resource_code` varchar(64) DEFAULT NULL,
  `detail` json DEFAULT NULL COMMENT '变更详情JSON',
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  `request_id` varchar(64) DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_user_time` (`user_id`,`create_time`),
  KEY `idx_module_time` (`module`,`create_time`),
  KEY `idx_resource` (`resource_type`,`resource_id`),
  KEY `idx_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `cn_hs_code` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `编码` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `名称` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `备注` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `第一法定单位` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `第二法定单位` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `监管条件` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `普通税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `优惠税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `出口税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `消费税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `增值税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `申报要素` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `import_batch` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hs_code` (`编码`(12))
) ENGINE=InnoDB AUTO_INCREMENT=12031 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `company` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_code` varchar(32) NOT NULL,
  `company_name_cn` varchar(128) NOT NULL,
  `company_name_jp` varchar(128) DEFAULT NULL,
  `company_type` varchar(32) DEFAULT NULL,
  `tax_id` varchar(64) DEFAULT NULL,
  `address` varchar(256) DEFAULT NULL,
  `contact_person` varchar(64) DEFAULT NULL,
  `contact_phone` varchar(32) DEFAULT NULL,
  `status` tinyint DEFAULT '1',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`company_code`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `consolidation_pool` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `update_time` datetime(6) NOT NULL,
  `container_threshold_cbm` decimal(10,4) DEFAULT NULL,
  `destination_port` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `plan_count` int DEFAULT NULL,
  `pool_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('OPEN','PENDING','LOADED','SHIPPED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_cbm` decimal(12,4) DEFAULT NULL,
  `total_weight_kg` decimal(12,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pool_code` (`pool_code`),
  KEY `idx_pool_status` (`status`),
  KEY `idx_pool_destination` (`destination_port`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `container` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `update_time` datetime(6) NOT NULL,
  `arrival_date` date DEFAULT NULL,
  `container_no` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `container_type` enum('GP20','GP40','HC40','HC45') COLLATE utf8mb4_unicode_ci NOT NULL,
  `departure_date` date DEFAULT NULL,
  `load_date` date DEFAULT NULL,
  `plan_count` int DEFAULT NULL,
  `pool_id` bigint DEFAULT NULL,
  `status` enum('CREATED','LOADED','DEPARTED','ARRIVED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_cbm` decimal(10,4) DEFAULT NULL,
  `total_weight_kg` decimal(12,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_container_no` (`container_no`),
  KEY `idx_container_status` (`status`),
  KEY `idx_container_pool` (`pool_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `demand_procurement_mapping` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `update_time` datetime(6) NOT NULL,
  `allocated_quantity` int NOT NULL,
  `demand_id` bigint NOT NULL,
  `procurement_id` bigint NOT NULL,
  `status` enum('进行中','已完成','已取消') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_demand_procurement` (`demand_id`,`procurement_id`),
  KEY `idx_mapping_demand` (`demand_id`),
  KEY `idx_mapping_procurement` (`procurement_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `department` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `dept_code` varchar(32) NOT NULL,
  `dept_name_cn` varchar(64) NOT NULL,
  `dept_name_jp` varchar(64) DEFAULT NULL,
  `parent_id` bigint DEFAULT NULL,
  `sort_order` int DEFAULT '0',
  `status` tinyint DEFAULT '1',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_company_dept` (`company_id`,`dept_code`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `domestic_customs_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `customs_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `procurement_id` bigint DEFAULT NULL,
  `logistics_plan_id` bigint DEFAULT NULL,
  `factory_id` bigint DEFAULT NULL,
  `product_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `estimated_value_cny` decimal(14,2) DEFAULT NULL,
  `status` enum('PENDING','SUBMITTED','CLEARED','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `container_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_domestic_customs_code` (`customs_code`),
  KEY `idx_dc_procurement_id` (`procurement_id`),
  KEY `idx_dc_logistics_plan_id` (`logistics_plan_id`),
  KEY `idx_dc_factory_id` (`factory_id`),
  KEY `idx_dc_product_code` (`product_code`),
  KEY `idx_dc_status` (`status`),
  KEY `idx_dc_create_time` (`create_time`),
  KEY `idx_dc_is_deleted` (`is_deleted`),
  KEY `idx_dc_container_no` (`container_no`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `example` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `update_time` datetime(6) NOT NULL,
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` tinyint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`),
  CONSTRAINT `example_chk_1` CHECK ((`status` between 0 and 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `factory` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `factory_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `factory_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` enum('TOOLS','TEXTILE','PLASTIC','ELECTRONICS','FURNITURE','AUTO_PARTS','SPORTS','PET','MEDICAL','CRAFTS','CHEMICAL','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `province` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `origin` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `county` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `rough_location` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `latitude` decimal(11,8) DEFAULT NULL,
  `contact_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_phone` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_wechat` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_qq` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cooperation_status` enum('ACTIVE','SUSPENDED','ELIMINATED','POTENTIAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_terms` enum('CASH','NET_30','NET_60','NET_90','CREDIT') COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `factory_code` (`factory_code`),
  UNIQUE KEY `uk_factory_name` (`factory_name`),
  KEY `idx_factory_code` (`factory_code`),
  KEY `idx_factory_name` (`factory_name`),
  KEY `idx_factory_category` (`category`),
  KEY `idx_factory_cooperation_status` (`cooperation_status`),
  KEY `idx_factory_province` (`province`),
  KEY `idx_factory_city` (`city`),
  KEY `idx_factory_is_deleted` (`is_deleted`),
  KEY `idx_factory_deleted` (`is_deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=506 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工厂/厂家信息表';
CREATE TABLE `flyway_schema_history` (
  `installed_rank` int NOT NULL,
  `version` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `script` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `checksum` int DEFAULT NULL,
  `installed_by` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `installed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `execution_time` int NOT NULL,
  `success` tinyint(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  KEY `flyway_schema_history_s_idx` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `japan_customs_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `customs_entry_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `procurement_id` bigint DEFAULT NULL,
  `domestic_customs_id` bigint DEFAULT NULL,
  `logistics_plan_id` bigint DEFAULT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('PENDING','IN_PROGRESS','CLEARED','FAILED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `arrival_date` date DEFAULT NULL,
  `customs_broker` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `broker_phone` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `broker_contact` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `import_duty_paid` decimal(14,2) DEFAULT NULL,
  `consumption_tax_paid` decimal(14,2) DEFAULT NULL,
  `clearance_date` date DEFAULT NULL,
  `arrival_port` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `declared_weight_kg` decimal(10,3) DEFAULT NULL,
  `declared_volume_cbm` decimal(10,4) DEFAULT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `container_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `factory_id` bigint DEFAULT NULL,
  `product_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_jp_customs_entry_no` (`customs_entry_no`),
  KEY `idx_jp_procurement_id` (`procurement_id`),
  KEY `idx_jp_domestic_customs_id` (`domestic_customs_id`),
  KEY `idx_jp_logistics_plan_id` (`logistics_plan_id`),
  KEY `idx_jp_status` (`status`),
  KEY `idx_jp_create_time` (`create_time`),
  KEY `idx_jp_is_deleted` (`is_deleted`),
  KEY `idx_jp_container_no` (`container_no`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `jp_hs_code` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `番号` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `品名` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `単位1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `単位2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `基本関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `暫定関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `WTO協定関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `特恵関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `特別特恵関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Singapore関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Mexico関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Malaysia関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Chile関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Thailand関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Indonesia関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Brunei関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `ASEAN関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Philippines関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Switzerland関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `VietNam関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `India関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Peru関税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `RCEP日ANZASEAN税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `RCEP中国税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `RCEP韓国税率` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `import_batch` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hs_code` (`番号`(12))
) ENGINE=InnoDB AUTO_INCREMENT=9695 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `logistics_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `container_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '货柜号（船公司提供，同批次货物填入相同货柜号）',
  `procurement_id` bigint DEFAULT NULL,
  `factory_id` bigint DEFAULT NULL,
  `product_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plan_type` enum('SEA','AIR','CONSOLIDATION') COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('PLANNED','BOOKED','IN_TRANSIT','DELIVERED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `cargo_length_cm` decimal(8,2) DEFAULT NULL,
  `cargo_width_cm` decimal(8,2) DEFAULT NULL,
  `cargo_height_cm` decimal(8,2) DEFAULT NULL,
  `cargo_volume_cbm` decimal(10,6) DEFAULT NULL,
  `cargo_weight_kg` decimal(10,4) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `requires_qc` bit(1) DEFAULT NULL,
  `container_id` bigint DEFAULT NULL,
  `pool_id` bigint DEFAULT NULL,
  `estimated_ship_date` date DEFAULT NULL,
  `actual_ship_date` date DEFAULT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `qc_record_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_code` (`plan_code`),
  KEY `idx_logistics_procurement` (`procurement_id`),
  KEY `idx_logistics_status` (`status`),
  KEY `idx_logistics_plan_type` (`plan_type`),
  KEY `idx_logistics_factory` (`factory_id`),
  KEY `idx_lp_product_code` (`product_code`),
  KEY `idx_lp_estimated_ship_date` (`estimated_ship_date`),
  KEY `idx_lp_create_time` (`create_time`),
  KEY `idx_lp_is_deleted` (`is_deleted`),
  KEY `idx_lp_container_no` (`container_no`),
  KEY `idx_logistics_qc_record` (`qc_record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `outbox` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `aggregate_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '聚合根类型：Order/Payment',
  `aggregate_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '聚合根 ID',
  `event_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '事件类型：OrderCreated/PaymentCompleted',
  `payload` json NOT NULL COMMENT '事件载荷',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=待发送，1=发送中，2=已发送，3=发送失败',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数',
  `max_retries` int NOT NULL DEFAULT '3' COMMENT '最大重试次数',
  `error_msg` text COLLATE utf8mb4_unicode_ci COMMENT '错误信息',
  `trace_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '链路追踪 ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_status_create` (`status`,`create_time`),
  KEY `idx_aggregate` (`aggregate_type`,`aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='消息 Outbox 表';
CREATE TABLE `permission` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `permission_code` varchar(64) NOT NULL,
  `permission_name_cn` varchar(64) NOT NULL,
  `permission_name_jp` varchar(64) NOT NULL,
  `module` varchar(32) NOT NULL,
  `action_` varchar(16) NOT NULL COMMENT 'READ/CREATE/UPDATE/DELETE/APPROVE/START/COMPLETE/EXPORT',
  `description` varchar(256) DEFAULT NULL,
  `sort_order` int DEFAULT '0',
  `status` tinyint DEFAULT '1',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `create_by` varchar(64) NOT NULL DEFAULT 'SYSTEM',
  `update_by` varchar(64) NOT NULL DEFAULT 'SYSTEM',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `permission_code` (`permission_code`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `position` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `position_code` varchar(32) NOT NULL,
  `position_name_cn` varchar(64) NOT NULL,
  `position_name_jp` varchar(64) DEFAULT NULL,
  `level_` int DEFAULT '0' COMMENT '职级（数字越大越高）',
  `company_id` bigint DEFAULT NULL COMMENT 'NULL=全局职务，非NULL=该公司私有',
  `status` tinyint DEFAULT '1',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `position_code` (`position_code`),
  KEY `idx_company` (`company_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `procurement` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `china_lead` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_company` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `destination` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estimated_price_jpy` decimal(14,2) DEFAULT NULL,
  `exchange_rate` decimal(10,4) NOT NULL,
  `factory_ship_date` date DEFAULT NULL,
  `japan_lead` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  `planned_ship_date` date DEFAULT NULL,
  `price_rmb` decimal(12,4) NOT NULL,
  `product_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_lead` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity` int NOT NULL,
  `status` enum('未定','予定','OEM','発注待','永康','直送','倉庫着','現地検品','検品','エア便','メーカー直送','輸出','通関','日本着','会計','完了','退货') COLLATE utf8mb4_unicode_ci NOT NULL,
  `tax_point` decimal(5,4) NOT NULL,
  `factory_id` bigint DEFAULT NULL COMMENT '???H??ID ?? factory.id',
  `actual_ship_date` date DEFAULT NULL,
  `billing_type` enum('ZHE_LU_KAI_PIAO','CHAO_HUI_TUI_SHUI','NO_REFUND','OTHER') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customs_remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instruction_manual` text COLLATE utf8mb4_unicode_ci,
  `material` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requires_qc` bit(1) DEFAULT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `carton_notes` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `after_sales_deadline` date DEFAULT NULL COMMENT '售后截止日（v1.10.0 新增）',
  `lead_time_days` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_procurement_product_code` (`product_code`),
  KEY `idx_procurement_status` (`status`),
  KEY `idx_procurement_create_time` (`create_time`),
  KEY `idx_procurement_factory_id` (`factory_id`),
  KEY `idx_procurement_sub_product_code` (`sub_product_code`),
  KEY `idx_procurement_order_date` (`order_date`),
  KEY `idx_proc_is_deleted` (`is_deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `procurement_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `procurement_id` bigint NOT NULL COMMENT '???注? FK',
  `factory_id` bigint DEFAULT NULL COMMENT '工厂 ID（????）',
  `factory_code` varchar(32) DEFAULT NULL COMMENT '工厂?号（下??刻）',
  `factory_name` varchar(128) DEFAULT NULL COMMENT '工厂名称（下??刻）',
  `factory_province` varchar(64) DEFAULT NULL COMMENT '工厂省?（下??刻）',
  `factory_city` varchar(64) DEFAULT NULL COMMENT '工厂城市（下??刻）',
  `factory_contact_name` varchar(64) DEFAULT NULL COMMENT '工厂?系人（下??刻）',
  `factory_contact_phone` varchar(32) DEFAULT NULL COMMENT '工厂??（下??刻）',
  `product_name_zh` varchar(255) DEFAULT NULL COMMENT '商品中文名（下??刻）',
  `product_name_ja` varchar(128) DEFAULT NULL COMMENT '商品日文名（下??刻）',
  `product_category` varchar(32) DEFAULT NULL COMMENT '商品分?（下??刻）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `update_by` varchar(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `procurement_id` (`procurement_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='?注?快照????下??刻的工厂和商品信息';
CREATE TABLE `product` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `master_code` varchar(32) NOT NULL,
  `sub_code` varchar(64) DEFAULT NULL,
  `jan_code` varchar(64) DEFAULT NULL,
  `name_zh` varchar(255) DEFAULT NULL,
  `name_en` varchar(255) DEFAULT NULL,
  `name_ja` varchar(128) DEFAULT NULL,
  `category` enum('OEM','ORDINARY','FACTORY_DIRECT') DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `color_name` varchar(64) DEFAULT NULL,
  `material` varchar(64) DEFAULT NULL,
  `material_ja` varchar(255) DEFAULT NULL,
  `origin` varchar(100) DEFAULT NULL,
  `warehouse` varchar(64) DEFAULT NULL,
  `quantities` int DEFAULT NULL,
  `carton_qty` int DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `unit_price_rmb` decimal(12,4) DEFAULT NULL,
  `amount_rmb` decimal(14,4) DEFAULT NULL,
  `tax_rate` decimal(5,4) DEFAULT NULL,
  `tax_point` decimal(5,4) DEFAULT NULL,
  `length_cm` decimal(8,2) DEFAULT NULL,
  `width_cm` decimal(8,2) DEFAULT NULL,
  `height_cm` decimal(8,2) DEFAULT NULL,
  `volume_cbm` decimal(10,6) DEFAULT NULL,
  `gross_weight_kg` decimal(10,4) DEFAULT NULL,
  `net_weight_kg` decimal(10,4) DEFAULT NULL,
  `hs_code` varchar(20) DEFAULT NULL,
  `hs_code_jp` varchar(20) DEFAULT NULL,
  `declaration_elements` text,
  `units_per_package` int DEFAULT NULL,
  `package_length_cm` decimal(8,2) DEFAULT NULL,
  `package_width_cm` decimal(8,2) DEFAULT NULL,
  `package_height_cm` decimal(8,2) DEFAULT NULL,
  `package_volume_cbm` decimal(10,6) DEFAULT NULL,
  `package_weight_kg` decimal(10,4) DEFAULT NULL,
  `requires_qc` bit(1) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `remarks` varchar(512) DEFAULT NULL,
  `last_used_date` date DEFAULT NULL,
  `create_by` varchar(64) NOT NULL DEFAULT '',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `update_by` varchar(64) NOT NULL DEFAULT '',
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_master_sub` (`master_code`,`sub_code`),
  KEY `idx_master_code` (`master_code`),
  KEY `idx_hs_code` (`hs_code`),
  KEY `idx_hs_code_jp` (`hs_code_jp`),
  KEY `idx_name_zh` (`name_zh`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_product_is_deleted` (`is_deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=5002 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `product_factory` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `product_id` bigint NOT NULL,
  `supplier_sku` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `factory_id` bigint NOT NULL,
  `is_preferred` bit(1) DEFAULT NULL,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `unit_price_rmb` decimal(12,4) DEFAULT NULL,
  `moq` int DEFAULT NULL,
  `lead_time_days` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_factory` (`product_id`,`factory_id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_factory_id` (`factory_id`)
) ENGINE=InnoDB AUTO_INCREMENT=726 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `qc_image` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `qc_record_id` bigint NOT NULL COMMENT '关联验货记录ID',
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'COS存储文件名',
  `original_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始文件名',
  `url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '访问URL',
  `size` bigint NOT NULL COMMENT '文件大小(字节)',
  `mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'MIME类型',
  `uploaded_by` bigint DEFAULT NULL COMMENT '上传人用户ID',
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '软删除标记',
  `deleted_at` datetime(6) DEFAULT NULL COMMENT '删除时间',
  `deleted_by` bigint DEFAULT NULL COMMENT '删除人用户ID',
  PRIMARY KEY (`id`),
  KEY `idx_qc_record_id` (`qc_record_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_filename` (`filename`),
  CONSTRAINT `fk_qc_image_qc_record` FOREIGN KEY (`qc_record_id`) REFERENCES `qc_record` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='验货记录图片表';
CREATE TABLE `qc_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `qc_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `procurement_id` bigint NOT NULL,
  `seller_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `product_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qc_user_id` bigint DEFAULT NULL,
  `qc_type` enum('ONSITE','REMOTE') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qc_date` date DEFAULT NULL,
  `result` enum('PASS','FAIL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('PENDING','COMPLETED','RETURN_REQUESTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `inspection_count` int DEFAULT NULL,
  `passed_count` int DEFAULT NULL,
  `defective_count` int DEFAULT NULL,
  `box_count` int DEFAULT NULL,
  `box_length_cm` decimal(8,2) DEFAULT NULL,
  `box_width_cm` decimal(8,2) DEFAULT NULL,
  `box_height_cm` decimal(8,2) DEFAULT NULL,
  `net_weight_per_unit` decimal(10,4) DEFAULT NULL,
  `gross_weight` decimal(10,4) DEFAULT NULL,
  `tax_inclusive_price` decimal(14,2) DEFAULT NULL,
  `material` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_refund` bit(1) DEFAULT NULL,
  `qc_standard` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `images` json DEFAULT NULL,
  `destination` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `shipment_batch_id` bigint DEFAULT NULL COMMENT '关联出货批次ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qc_code` (`qc_code`),
  KEY `idx_qc_procurement` (`procurement_id`),
  KEY `idx_qc_result` (`result`),
  KEY `idx_qc_date` (`qc_date`),
  KEY `idx_qc_status` (`status`),
  KEY `idx_qc_is_deleted` (`is_deleted`),
  KEY `idx_qc_shipment_batch` (`shipment_batch_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `replenishment_demand` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `demand_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `demand_type` enum('REPLENISHMENT','NEW_PURCHASE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `product_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `japan_lead` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `remarks` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  `destination` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linked_procurement_id` bigint DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'v2.0.0: 子?号全?',
  `image_url` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `demand_code` (`demand_code`),
  KEY `idx_demand_status` (`status`),
  KEY `idx_demand_type` (`demand_type`),
  KEY `idx_demand_product_code` (`product_code`),
  KEY `idx_demand_is_deleted` (`is_deleted`),
  KEY `idx_demand_quantity` (`quantity`),
  KEY `idx_demand_destination` (`destination`),
  KEY `idx_demand_sub_product_code` (`sub_product_code`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='??需求?';
CREATE TABLE `role` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `role_code` varchar(32) NOT NULL,
  `role_name_cn` varchar(64) NOT NULL,
  `role_name_jp` varchar(64) NOT NULL,
  `role_type` varchar(16) DEFAULT NULL COMMENT 'SYSTEM/BUSINESS',
  `description` varchar(256) DEFAULT NULL,
  `is_editable` tinyint DEFAULT '1' COMMENT '0=系统内置不可编辑',
  `status` tinyint DEFAULT '1',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `create_by` varchar(64) NOT NULL DEFAULT 'SYSTEM',
  `update_by` varchar(64) NOT NULL DEFAULT 'SYSTEM',
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_code` (`role_code`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `role_permission` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `role_id` bigint NOT NULL,
  `permission_id` bigint NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_permission` (`role_id`,`permission_id`),
  KEY `idx_permission` (`permission_id`)
) ENGINE=InnoDB AUTO_INCREMENT=272 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `saga_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `saga_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Saga 实例 ID',
  `step_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '步骤名称',
  `step_order` int NOT NULL DEFAULT '0' COMMENT '步骤顺序',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=待执行，1=成功，2=补偿中，3=已补偿，4=补偿失败',
  `error_msg` text COLLATE utf8mb4_unicode_ci COMMENT '错误信息',
  `trace_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '链路追踪 ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_saga_id` (`saga_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Saga 执行日志表';
CREATE TABLE `sales_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `record_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `procurement_id` bigint DEFAULT NULL,
  `product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sub_product_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sales_channel` enum('AMAZON','MERCALI','SELF_SITE','OTHER') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('LISTED','LOW_STOCK','OUT_OF_STOCK','DISCONTINUED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `listing_date` date DEFAULT NULL,
  `initial_stock` int DEFAULT NULL,
  `current_stock` int DEFAULT NULL,
  `safety_stock` int DEFAULT NULL,
  `sales_quantity` int DEFAULT NULL,
  `returned_quantity` int DEFAULT NULL,
  `return_rate` decimal(6,4) DEFAULT NULL,
  `selling_price_jpy` decimal(14,2) DEFAULT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_sr_product_code` (`product_code`),
  KEY `idx_sr_procurement_id` (`procurement_id`),
  KEY `idx_sr_status` (`status`),
  KEY `idx_sr_sales_channel` (`sales_channel`),
  KEY `idx_sr_create_time` (`create_time`),
  KEY `idx_sr_is_deleted` (`is_deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `shipment_batch` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(6) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `update_time` datetime(6) NOT NULL,
  `actual_ship_date` date DEFAULT NULL,
  `batch_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `factory_ship_date` date DEFAULT NULL,
  `procurement_id` bigint NOT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipment_quantity` int NOT NULL,
  `status` enum('待验货','验货中','已验货','已取消') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sb_procurement` (`procurement_id`),
  KEY `idx_sb_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `signing_key` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `kid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '密钥 ID（写入 JWT kid header）',
  `public_key_pem` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '公钥 PEM（不含私钥）',
  `private_key_path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '私钥文件路径（不含私钥内容）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=INACTIVE，1=ACTIVE',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '密钥创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_kid` (`kid`),
  UNIQUE KEY `idx_signing_key_kid` (`kid`),
  KEY `idx_status` (`status`),
  KEY `idx_signing_key_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RS256 签名密钥表';
CREATE TABLE `tax_refund_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `refund_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `procurement_id` bigint DEFAULT NULL,
  `japan_customs_id` bigint DEFAULT NULL,
  `status` enum('APPLYING','COMPLETED','NO_REFUND') COLLATE utf8mb4_unicode_ci NOT NULL,
  `billing_type` enum('ZHE_LU_KAI_PIAO','CHAO_HUI_TUI_SHUI','NO_REFUND','OTHER') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price_rmb` decimal(14,4) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `tax_point` decimal(6,4) DEFAULT NULL,
  `exchange_rate` decimal(10,6) DEFAULT NULL,
  `estimated_refund_rmb` decimal(14,4) DEFAULT NULL,
  `actual_refund_rmb` decimal(14,4) DEFAULT NULL,
  `refund_date` date DEFAULT NULL,
  `refund_bank` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remarks` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `create_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `update_by` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `is_deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  KEY `idx_tr_procurement_id` (`procurement_id`),
  KEY `idx_tr_japan_customs_id` (`japan_customs_id`),
  KEY `idx_tr_status` (`status`),
  KEY `idx_tr_refund_date` (`refund_date`),
  KEY `idx_tr_create_time` (`create_time`),
  KEY `idx_tr_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_code` varchar(32) NOT NULL COMMENT '用户编码 U-XXXX',
  `username` varchar(64) NOT NULL COMMENT '登录账号',
  `password_hash` varchar(255) NOT NULL COMMENT 'BCrypt哈希',
  `name_cn` varchar(64) DEFAULT NULL COMMENT '中文姓名',
  `name_jp` varchar(64) DEFAULT NULL COMMENT '日文姓名',
  `email` varchar(128) NOT NULL,
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `avatar_url` varchar(512) DEFAULT NULL COMMENT '头像URL',
  `company_id` bigint DEFAULT NULL COMMENT '所属公司 FK → company.id',
  `department_id` bigint DEFAULT NULL COMMENT '所属部门 FK → department.id',
  `customs_code` varchar(64) DEFAULT NULL COMMENT '报关员备案号',
  `customs_license` varchar(128) DEFAULT NULL COMMENT '报关员证号',
  `language` varchar(8) DEFAULT 'zh',
  `timezone` varchar(16) DEFAULT 'CST',
  `status` tinyint DEFAULT '1' COMMENT '1=正常 0=禁用',
  `last_login_time` datetime(3) DEFAULT NULL COMMENT '最后登录时间',
  `last_login_ip` varchar(45) DEFAULT NULL COMMENT '最后登录IP',
  `registration_status` varchar(16) DEFAULT 'APPROVED' COMMENT 'APPROVED/PENDING/REJECTED',
  `reject_reason` varchar(256) DEFAULT NULL COMMENT '拒绝原因（REJECTED时填写）',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `create_by` varchar(64) NOT NULL DEFAULT 'SYSTEM',
  `update_by` varchar(64) NOT NULL DEFAULT 'SYSTEM',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_code` (`user_code`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `uk_code` (`user_code`),
  UNIQUE KEY `uk_username` (`username`),
  UNIQUE KEY `uk_email` (`email`),
  KEY `idx_company` (`company_id`),
  KEY `idx_dept` (`department_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_position` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `position_id` bigint NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_position` (`user_id`,`position_id`),
  KEY `idx_position` (`position_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_role` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),
  KEY `idx_role` (`role_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
  `demand_id` tinyint NOT NULL,
  `demand_code` tinyint NOT NULL,
  `demand_type` tinyint NOT NULL,
  `demand_product_code` tinyint NOT NULL,
  `demand_sub_product_code` tinyint NOT NULL,
  `demand_quantity` tinyint NOT NULL,
  `demand_destination` tinyint NOT NULL,
  `demand_japan_lead` tinyint NOT NULL,
  `demand_status` tinyint NOT NULL,
  `linked_procurement_id` tinyint NOT NULL,
  `demand_image_url` tinyint NOT NULL,
  `demand_create_time` tinyint NOT NULL,
  `demand_update_time` tinyint NOT NULL,
  `procurement_id` tinyint NOT NULL,
  `procurement_code` tinyint NOT NULL,
  `procurement_factory_id` tinyint NOT NULL,
  `procurement_product_code` tinyint NOT NULL,
  `procurement_sub_product_code` tinyint NOT NULL,
  `procurement_quantity` tinyint NOT NULL,
  `procurement_price_rmb` tinyint NOT NULL,
  `procurement_tax_point` tinyint NOT NULL,
  `procurement_exchange_rate` tinyint NOT NULL,
  `procurement_billing_type` tinyint NOT NULL,
  `procurement_estimated_price_jpy` tinyint NOT NULL,
  `procurement_order_date` tinyint NOT NULL,
  `procurement_factory_ship_date` tinyint NOT NULL,
  `procurement_planned_ship_date` tinyint NOT NULL,
  `procurement_actual_ship_date` tinyint NOT NULL,
  `procurement_lead_time_days` tinyint NOT NULL,
  `procurement_product_lead` tinyint NOT NULL,
  `procurement_japan_lead` tinyint NOT NULL,
  `procurement_china_lead` tinyint NOT NULL,
  `procurement_destination` tinyint NOT NULL,
  `procurement_customer_company` tinyint NOT NULL,
  `procurement_status` tinyint NOT NULL,
  `procurement_create_time` tinyint NOT NULL,
  `snapshot_factory_id` tinyint NOT NULL,
  `snapshot_factory_code` tinyint NOT NULL,
  `snapshot_factory_name` tinyint NOT NULL,
  `snapshot_factory_province` tinyint NOT NULL,
  `snapshot_factory_city` tinyint NOT NULL,
  `snapshot_factory_contact_name` tinyint NOT NULL,
  `snapshot_factory_contact_phone` tinyint NOT NULL,
  `snapshot_product_name_zh` tinyint NOT NULL,
  `snapshot_product_name_ja` tinyint NOT NULL,
  `snapshot_product_category` tinyint NOT NULL,
  `qc_record_id` tinyint NOT NULL,
  `qc_code` tinyint NOT NULL,
  `qc_result` tinyint NOT NULL,
  `qc_inspection_count` tinyint NOT NULL,
  `qc_passed_count` tinyint NOT NULL,
  `qc_defective_count` tinyint NOT NULL,
  `qc_box_count` tinyint NOT NULL,
  `qc_box_length_cm` tinyint NOT NULL,
  `qc_box_width_cm` tinyint NOT NULL,
  `qc_box_height_cm` tinyint NOT NULL,
  `qc_net_weight_per_unit` tinyint NOT NULL,
  `qc_gross_weight` tinyint NOT NULL,
  `qc_date` tinyint NOT NULL,
  `qc_status` tinyint NOT NULL,
  `qc_create_time` tinyint NOT NULL,
  `logistics_plan_id` tinyint NOT NULL,
  `logistics_plan_code` tinyint NOT NULL,
  `logistics_container_no` tinyint NOT NULL,
  `logistics_plan_type` tinyint NOT NULL,
  `logistics_cargo_length_cm` tinyint NOT NULL,
  `logistics_cargo_width_cm` tinyint NOT NULL,
  `logistics_cargo_height_cm` tinyint NOT NULL,
  `logistics_cargo_volume_cbm` tinyint NOT NULL,
  `logistics_cargo_weight_kg` tinyint NOT NULL,
  `logistics_requires_qc` tinyint NOT NULL,
  `logistics_estimated_ship_date` tinyint NOT NULL,
  `logistics_actual_ship_date` tinyint NOT NULL,
  `logistics_status` tinyint NOT NULL,
  `logistics_create_time` tinyint NOT NULL,
  `step1_status` tinyint NOT NULL,
  `step2_status` tinyint NOT NULL,
  `step3_status` tinyint NOT NULL,
  `step4_status` tinyint NOT NULL,
  `step5_status` tinyint NOT NULL,
  `step6_status` tinyint NOT NULL,
  `step7_status` tinyint NOT NULL,
  `step8_status` tinyint NOT NULL,
  `domestic_customs_id` tinyint NOT NULL,
  `domestic_customs_no` tinyint NOT NULL,
  `domestic_hs_code` tinyint NOT NULL,
  `domestic_declaration_date` tinyint NOT NULL,
  `domestic_export_port` tinyint NOT NULL,
  `domestic_declared_value_rmb` tinyint NOT NULL,
  `domestic_customs_status` tinyint NOT NULL,
  `domestic_create_time` tinyint NOT NULL,
  `japan_customs_id` tinyint NOT NULL,
  `japan_customs_entry_no` tinyint NOT NULL,
  `japan_arrival_date` tinyint NOT NULL,
  `japan_customs_broker` tinyint NOT NULL,
  `japan_broker_phone` tinyint NOT NULL,
  `japan_import_duty_paid` tinyint NOT NULL,
  `japan_consumption_tax_paid` tinyint NOT NULL,
  `japan_clearance_date` tinyint NOT NULL,
  `japan_customs_status` tinyint NOT NULL,
  `japan_create_time` tinyint NOT NULL,
  `tax_refund_id` tinyint NOT NULL,
  `tax_refund_amount` tinyint NOT NULL,
  `tax_refund_date` tinyint NOT NULL,
  `tax_refund_status` tinyint NOT NULL,
  `tax_refund_create_time` tinyint NOT NULL,
  `sales_record_id` tinyint NOT NULL,
  `sales_record_code` tinyint NOT NULL,
  `sales_channel` tinyint NOT NULL,
  `sales_listing_date` tinyint NOT NULL,
  `sales_initial_stock` tinyint NOT NULL,
  `sales_current_stock` tinyint NOT NULL,
  `sales_safety_stock` tinyint NOT NULL,
  `sales_sales_quantity` tinyint NOT NULL,
  `sales_returned_quantity` tinyint NOT NULL,
  `sales_return_rate` tinyint NOT NULL,
  `sales_selling_price_jpy` tinyint NOT NULL,
  `sales_status` tinyint NOT NULL,
  `sales_create_time` tinyint NOT NULL
) ENGINE=MyISAM */;
SET character_set_client = @saved_cs_client;
