-- =============================================================
-- Migration: V25__product_column_reorder.sql
-- Date: 2026-04-23
-- Desc: Reorder product columns in logical groups
-- =============================================================
-- This migration reorders columns in the product table.
-- Use the Python script migrate_product_column_order.py to execute.
-- Run: python migrate_product_column_order.py
--
-- New column order (logical grouping):
--   1. 标识:   id, master_code, sub_code, jan_code
--   2. 名称:   name_zh, name_en, name_ja
--   3. 分类:   category, status, color_name
--   4. 材质:   material, material_ja
--   5. 来源:   origin, warehouse
--   6. 业务量: quantities, carton_qty, unit, unit_price_rmb, amount_rmb
--   7. 税率:   tax_rate, tax_point
--   8. 单品尺寸: length_cm, width_cm, height_cm, volume_cbm
--   9. 单品重量: gross_weight_kg, net_weight_kg
--   10. 报关:  hs_code, hs_code_jp, declaration_elements
--   11. 外箱:  units_per_package, package_*
--   12. 质检:  requires_qc
--   13. 其他:  image_url, remarks, last_used_date
--   14. 审计:  create_by, create_time, is_deleted, update_by, update_time
