-- ============================================================
-- V28: 补货需求单 v1.6.0 schema
-- 说明：V10_2 的旧版 schema（quantity/destination/linked_procurement_id）
--       已废弃，v1.6.0 统一为 JSON 字段。
-- 此文件记录最终正确结构（参考用，Flyway 禁用时由 Hibernate ddl-auto 维护）。
-- ============================================================

-- v1.6.0 正确结构：
-- id                  BIGINT PRIMARY KEY AUTO_INCREMENT
-- demand_code         VARCHAR(32)  NOT NULL
-- demand_type         VARCHAR(32)  NOT NULL
-- product_code        VARCHAR(32)  NOT NULL
-- sub_product_code    TEXT         -- v1.6.0: JSON数组 [{"subCode":"be","quantity":50,"destination":"东京"},...]
-- japan_lead          VARCHAR(64)
-- status              VARCHAR(32)  NOT NULL
-- linked_demand_items TEXT         -- v1.6.0: JSON数组 [{"linkedProcurementId":101,"subCode":"be"},...]
-- remarks             VARCHAR(512)
-- create_time, update_time, create_by, update_by, is_deleted (BaseEntity 审计字段)

-- V27 已执行变更（生产环境手动 ALTER）：
-- ALTER TABLE replenishment_demand MODIFY COLUMN sub_product_code TEXT;
-- ALTER TABLE replenishment_demand MODIFY COLUMN linked_demand_items TEXT;
-- ALTER TABLE replenishment_demand DROP COLUMN IF EXISTS quantity;
-- ALTER TABLE replenishment_demand DROP COLUMN IF EXISTS destination;
-- ALTER TABLE replenishment_demand DROP COLUMN IF EXISTS linked_procurement_id;
