-- V30: 从 list7 导入船只（ship_name → ship 表）
-- 唯一船只: 374

INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC YOKOHAMA V.2112E', 'LIST7-001', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('7', 'LIST7-002', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('8', 'LIST7-003', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('9', 'LIST7-004', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('10', 'LIST7-005', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HE SHENG V.2108E', 'LIST7-006', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('<待定>', 'LIST7-007', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN VENUS V.0061E', 'LIST7-008', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC HONGKONG V.2110E', 'LIST7-009', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GLORY SHENGDONG V.2111E', 'LIST7-010', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INTEGRA V.2105N', 'LIST7-011', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL LE HAVRE V.140N', 'LIST7-012', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILLENNIUM BRIGHT 21005N', 'LIST7-013', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CSCL NAGOYA 361E', 'LIST7-014', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN VENUS V.0062E', 'LIST7-015', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 222 V.0LP6UN1NC', 'LIST7-016', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS KEELUNG / V.2106E', 'LIST7-017', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC JAKARTA 2107', 'LIST7-018', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS OSAKA 2113E', 'LIST7-019', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ATLANTIC EAST /2112E', 'LIST7-020', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM INITIATIVE V.272N', 'LIST7-021', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SUNSHINE BANDAMA/2105N', 'LIST7-022', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ESTIMA', 'V.2113E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN VENUS V.0064E', 'LIST7-024', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GLORY GUANDONG 2112N', 'LIST7-025', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ISARA BHUM', '2114E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JRS CORVUS', 'V.2114E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC DALIAN', 'V.2109N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS OSAKA', 'V.2115E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS KEELUNG', 'V.2107E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN VENUS', '0065E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC YOKOHAMA', '的22', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 222', '我', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LIOBA', 'V.142N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC LIAONING', 'V.2105N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC HONGKONG', 'V.2115E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CSCL NAGOYA', 'V.365E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC TOKYO', 'V.2115E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILLENNIUM BRIGHT', 'V.21007N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GLORY ZHENDONG', 'V.2115N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JJ TOKYO', 'V.2116E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CENTENNIAL', 'V.011N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OCEANIA DRAGON', 'V.2107N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS DALIAN', '2117E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('STRIDE', 'V.1477-050N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC TOYOHASHI', 'V.2121E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SHIDAO', 'V.2109N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU', '28 V.2112E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SUNSHINE BANDAMA', '2107N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('FENGYUNHE', 'V.1779N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CONSTANCY', 'V.002N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SENDAI', '2129E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GLORY GUANDONG', 'V.2118N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAIYUNHE', 'V.1779N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ACACIA MAKOTO', 'V.2120E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM INITIATIVE', 'V.276N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIANG SHUN', 'V.2120E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC TAICANG', '2129E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC MANILA', 'V.2122E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('THORSTAR', 'V.21004N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HF WEALTH', 'V.2131E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EAS LINE LIANYUNGANG', '2121E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('KMTC YOKOHAMA', 'V.2105N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC JAKARTA', 'V.2111N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ZHONG GU NAN HAI', 'V.2112E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CONTINENT', 'V.20N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAPE FORBY', 'V.1783N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('PROS HOPE', 'V.063E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL CHARLESTON', 'V.201N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC KOBE', 'V.2139E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS SHANGHAI', '2128E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC WEIHAI', '2135E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL NAGOYA', 'V.153N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC BANGKOK', 'V.2113N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIU HONG', 'V.2131E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC MACAO', 'V.2119N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC GUANGDONG', 'V.2115N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC KAWASAKI', 'V.2117N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CONTINUITY', 'V.002N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('RESOLUTION', '2133E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('QIU JIN', 'V.2133E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC QINZHOU', '2145E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CORE', '1829-025N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN CONTINENTAL', 'V.0086E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC LIANYUNGANG', '2121N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ACACIA TAURUS', '2136A', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC TIANJIN', 'V.2146E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC KEELUNG', 'V.2117N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A ROKU', 'V.2140E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CLEAR', 'V.1498-018N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INTEGRA', 'V.2119', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ANASSA', '21002N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JI RUN', 'V.2141', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL SAVANNAH', 'V.410N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC KANTO', '2121N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HANSA FLENSBURG', 'V.034N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC JIANGSU', 'V.2121N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CHARM', 'V.1839-026N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SUBIC', 'V.2159E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MING ZHOU', '98 V.2101E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER COPE 1838-033N', '1838-033N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CAPACITY V.013N', 'V.013N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LUDWIG SCHULTE V.024N', 'V.024N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('KANWAY GALAXY V.2149E', 'V.2149E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER COPE', 'V.1843-034N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WES SINA 237E', '237E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL DALIAN', 'V.666N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OREA', 'V.018N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CHUN JIN', 'V.2149E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ACACIA ARIES', 'V.2150E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INTRA BHUM', 'V.130E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAPE ORIENT', 'V.109N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A FUKU', 'V.2201E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EASLINE  LIANYUNGANG', 'V.2201E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS BANGKOK', 'V.2201E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WES SINA', 'V.241E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC YOKKAICHI', 'V.2203E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CONTESSA', 'V.016E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('RENOWN', 'V.2203E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC TAICANG', 'V.2203E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU', '16V.2201E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ISARA BHUM', 'V.2207E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HALCYON', 'V.478E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU66', '2205E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HANSA  DUBURG', '22001N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('STRAITS CITY', '2210E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CAPACITY', 'V.016N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC BUSAN', '2213E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HAI FENG HAI KOU', 'V.2209N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('KANWAY GALAXY', '2212E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU 16', 'V.2208E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU28', 'V.2208E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('REFLECTION', 'V.2219N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EASLINE YANTAI', '2213E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILLENNIUM BRIGHT', 'V.22007N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CONTINENT', 'V.029N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JRS CORVUS', 'V.22013E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JAN', 'V.22006N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC KWANGYANG', 'V.2222E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ZHONG GU BO HAI', 'V.2207N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC LAEM CHABANG', 'V.2207N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU 68', 'V.2211E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC FUJIAN', 'V.2207N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ACACIA MING', '2218E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC OSAKA', 'V.2211N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A KIBO', '2219E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC JIADE', 'V.2205N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SHIMIZU', '2235E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIU HONG', 'V.2220E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('RUN LONG', 'V.2219E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ACACIA WA', 'V.2223E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HUANGHAI ADVANCE', 'V.2224E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TAN CANG GLORY', 'V.2226E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A BOTE', '2225E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A SUKAI', '2227E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS OSAKA', 'V.22010N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC NAGOYA', 'V.2227E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC HOCHIMINH', 'V.2235E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('AKITETA', 'V.007N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL NEW ZEALAND', '114N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('QING YUN HE', 'V.032N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MING ZHOU22', 'V.2201E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MING ZHOU26', 'V.2210E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ASIATIC WAVE', 'V.551E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MINGZHOU 18', 'V.2203E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM INTERACTION', 'V.233N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SKY CHALLENGE', 'V.22010N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ASIATIC REUNION', 'V.008E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC FANGCHENG', 'V.2229E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GUANG PING', 'V.006E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI161', 'V.441N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LANTAU BAY', '2253E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HUA HANG HAN YA 2', 'V.2218E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC LIDE', 'V.2223N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAPE FRANKLIN', 'V.2221N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GREEN CELEBRITY', 'V.1894', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS BEIJING', '2248E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WANA BHUM', '081S', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SHANGDE', 'V.2221N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CROWN', 'V.030N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GLORY SEASON', 'V.2250E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HUA HANG HAN YA 1', 'V.2218E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK NASSJO', '248N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAPE FARO', 'V.N038E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN ENTERPRISE', 'v.0117E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CONCISE', 'V.022N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('KMTC  GWANGYANG', 'V.2213N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LALIT BHUM', 'V.22017N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A  XINXIA', '2302E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TIGER LIANYUNGANG', 'V.2301N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  MOJI', 'V.2301N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN  HAI290', 'V.N020E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC XINGDE', 'V.2303N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC QINGDAO', 'V.2305N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS TIANJIN', 'V.23002N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NAWATA BHUM', '2307E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A KEIGA', 'V.2310E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS KAOHSIUNG', 'V.23003N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI282', 'V.172E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JINYUNHE', 'V.1829N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 265', 'V.N358E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JI YUAN', 'V.2313E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC WENDE', 'V.2307N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS  XIAMEN', 'V.23003N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  ANHE', 'V.2319E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HANSA FRESENBURG', 'V.23005N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HF FORTUNE', 'V.2315N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OKEE PIPER', 'V.23005N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ATLANTIC EAST', '2317E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK  NUSSFJORD', 'V.317N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CONNECT', '1582-020N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER COMPOSE', 'V.1583-041N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI281', 'V.N239', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CANDID', '043N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK NORESUND', 'V.323N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  SHENGDE', 'V.2311N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MANET', '23017N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('RUN  SHENG', '2326E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  HEBEI', 'V.2315N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  RUIMING', 'V.2315', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NUUK  MAERSK', 'V.326N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  GUANGDONG', 'V.2315N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HANSA  COLOMBO', '2335E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CEBU', 'V.23004N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INSIGHT', '2336E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NORDBORG MAERSK', '334N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SHENG LI JI', 'V.2334', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LISBOA', 'V.2339E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A ONTAKE', '2340E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HS HONG KONG', '2319E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS  GUANGZHOU', 'V.23016N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER  CONCERT', 'V.033N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('PHOENIX D', '341N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER  CONCISE', 'V.033N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ASIATIC QUEST', 'V.2346E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NIIGATA TRADER', '2324E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DA   BAO', '2351E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN  HAI523', 'V.N022', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INFINITY', 'V.2348E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ACACIA LIBRA', '2401E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SUNNY LAVENDER', 'V.2325E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HAKATA SEOUL', '2401W', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILD SONATA/', '2403E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL LE HAVRE', 'V.177N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL CHARLESTON', 'V.231N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('STAR  CHASER', 'V.2402E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC RUNDE', 'V.2405N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EPONYMA', 'V.113E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS COLOMBO', 'V.24002N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CA TOKYO', '2401E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL  NAGOYA', 'V.197N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MITRA  BHUM', 'V.2402E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  XIANDE', 'V.2407N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN  HAI 322', 'V.N028', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC ZHEJIANG', 'V.2409N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  KEELUNG', 'V.2407N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  SUBIC', 'V.2421E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('THE  TAICHUNG', 'V.24005N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  SHANDONG', 'V.2409N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  YUHE', '2435E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER  CHANT', 'V.082N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN  MING ZHOU106', 'V.2402E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HENG  YU', 'V2412E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  YANTAI', 'V.2433', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 278', 'V.N026E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAPE  SYROS', 'V.24067N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU 66', 'V.2414E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILD  TEMPO', '2422E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LUDWIG SCHULTE', '420N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL ZHOUSHAN', 'V.269N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TORRES STRAIT', '423N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC FENGHE', 'V.2417N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A  ATAGO', '2428E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SINOTRANS KAOHSIUNG', '2414E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('KAI  PING', 'V.2402E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ASIAN ACE', '424N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 326', 'V.N039', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HELGOLAND', 'V.429N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A SUWA', 'V.2430E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS HOCHIMINH', 'V.24004N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CNC SULAWESI', 'V.3CGEWN1NC', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JRS CARINA', 'V.2433E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HANSA HARBURG', '430N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('K-PACIFIC', 'V.2401E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SEOUL  GLOW', '433N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HANSA BITBURG', '434N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ONE  MUNCHEN', '039W', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('LUDWIGSHAFEN EXPRESS', '047W', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK NINGBO', '439N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CREDIBILITY', 'V.130N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('BAL BOAN', 'V.2401E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('AS SERENA', 'V.443N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  CHANGDE', 'V.2421N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  MINGDE', 'V.2421N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN  HAI  333', 'V.001N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INVICTA', '046E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TOKYO TOWER', 'V.001N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  HAODE', 'V.2437N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER BOARD', 'V.062N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ERASMUS LEO', 'V.447N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('DONGJIN VOYAGER', 'V.448N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILD SONATA', 'V.2446N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  HANSHIN', 'V.2425N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC  PINGHE', '2437E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JIFA BOHAI', 'V.2439E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NUUK MAERSK', 'V.449N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM CERTAINTY', 'V.065N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HF LUCKY', 'V.2461E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('AMOUREUX', 'V.2501N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CONSERO', 'V.2405N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('HE YUAN 1', '2501E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MARTI STAR II', 'V.2403N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NAKSKOV MAERSK', 'V.502N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 322', 'V.N041', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM INCREMENT', 'V.312N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('AS SOPHIA', 'V.507N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MING ZHOU 108', 'V.2501E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('AS ANNE', '003N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MCC SHENZHEN', '510N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MTT SAPANGAR', '512N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('VANCOUVER', 'V.041N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC RENHE', 'V.2509N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('PHEN BASIN', 'V.113N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK VALENCIA', '514N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INTERASIA TRIBUT', 'V.N002', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GSL MAREN', '014N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CNC JAWA', 'V.OQIKONINC', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER COMMAND', 'V1688-064N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('BOHAI STAR', 'V.2522E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SHUNHE', 'V.2515N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('PACANDA', 'V.2501E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ZHONG GU TIAN JIN', 'V.2523E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A KAKOGAWA', 'V.2525E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CAPE BONAVISTA', 'V.OQIKYNINC', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('GLORY SHENGDONG', 'V.2526E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 292', 'V.N052E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INTERASIA ELEVATE', 'V.N055', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 370', 'V.N017', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('OOCL NORFOLK', 'V.293N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS NAGOYA', 'V.25102N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM INSTRUCTION', 'V.332N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MING ZHOU 98', 'V.2501E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CHANT', 'V.2305-100N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 296', 'V.N045E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('WAN HAI 175', 'V.N140E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('YM INAUGURATION', 'V.322N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TAICHUNG', 'V.415N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC MINHE', 'V.2521N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A FLENSBURG', 'V.2540E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('CCNI ANGOL', '542N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK JIANGYIN', '544N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('XIN MING ZHOU96', 'V.2501E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MORESBY CHIEF', 'V.010N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MARINA SAPPHIRE', '545N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SMC YANTAI', '2545E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('NEW MINGZHOU 60', 'V.2501E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('EVER CENTER', 'V.2048-070N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('STAR RANGER', 'LIST7-358', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK NORDDAL', '602N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('RONG XING 1', 'V.2603E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('A GALAXY', '2603E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ERASMUS QUEEN', '604N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('INESSA', 'V073N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('JOSCO ALMA', '2603E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TS HAKATA', 'V.26001N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('FU TU LIAN XING', 'V.2609E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SHENZHEN', '2606S', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MAERSK VARNA', '610N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('TANG SHAN GANG JI 2', '2606E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('IRENES RAINBOW', 'V.029N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('SITC SHUNDE', 'V.2609N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('PRESIDENT LB JOHNSON', '0DBO9E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('ASL HAIPHONG', 'V.2602E', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
INSERT IGNORE INTO ship (ship_name, ship_number, create_by, create_time, update_by, update_time, is_deleted) VALUES ('MILD JASMINE', 'V.2617N', 'SYSTEM', NOW(3), 'SYSTEM', NOW(3), FALSE);
